
import { CatalogEntry, Rank } from './types';

export const OPERATIVE_TYPES = [
  "OPERATIVO DISUASION Y PREVENCION CON POLICIA MONTADA",
  "OPERATIVO DISUASION Y PREVENCION CON AGRUPAMIENTO K9",
  "OPERATIVO C.E.M.",
  "OPERATIVO INTERINSTITUCIONAL FRONTERAS",
  "OPERATIVO PEGASO",
  "OPERATIVO RECONSTRUCCION POR LA PAZ",
  "OPERATIVO SENDERO SEGURO",
  "OPERATIVO DE PROXIMIDAD, DISUASION Y PREVENCION DEL DELITO",
  "OPERATIVO DE PROXIMIDAD Y ESCUELA SEGURA",
  "OPERATIVO LECHERIA SEGURA",
  "OPERATIVO REUNION VECINAL",
  "OPERATIVO TIANGUIS",
  "OPERATIVO PROXIMIDAD EN EL TRANSPORTE Y PASAJERO SEGURO",
  "OPERATIVO VELADA"
];

export const REGIONS = [
  "REGION 1", "REGION 2", "REGION 3", "REGION 4", "REGION 5", "REGION 6", "REGION 7",
  "TRANSITO", "GOE", "RECUPERACION DE VEHICULOS", "PROXIMIDAD", "INTELIGENCIA",
  "ASTROS", "PREVENCION DEL DELITO", "CUARTEL", "MONTADA", "K-9"
];

// Corrected mixed-case strings to match Rank type in types.ts
export const RANKS: Rank[] = [
  'Comisario', 'Subdirector', 'Tecnico Operativo', 'Encargado Regonal', 'Jefe de turno', 'Jefe de Cuadrante', 'Patrullero'
];

export const INSTITUTIONS = [
  "SEDENA", "MARINA", "GUARDIA NACIONAL", "POLICIA ESTATAL", "MUNICIPAL",
  "FISCALIA GENERAL DE JUSTICIA", "FISCALIA ESPECIALIZADA", "GRUPO ESPECIAL"
];

export const REGION_QUADRANTS: Record<string, string[]> = {
  "REGION 1": ["11", "12", "13", "14", "15", "16", "17"],
  "REGION 2": ["21", "22", "23", "24", "25"],
  "REGION 3": ["31", "32", "33", "34", "35", "36", "37", "38"],
  "REGION 4": ["41", "42", "43", "44", "45", "46", "47", "48"],
  "REGION 5": ["51", "52", "53", "54"],
  "REGION 6": ["61", "62", "63", "64", "65", "66", "67", "68"],
  "REGION 7": ["71", "72", "73", "74", "75", "76", "77"]
};

export const ALL_QUADRANTS = Array.from(new Set(Object.values(REGION_QUADRANTS).flat())).sort();

export const COLONIA_CATALOG: CatalogEntry[] = [
  // REGION 1
  { region: "REGION 1", quadrant: "11", colony: "18 DE AGOSTO" },
  { region: "REGION 1", quadrant: "11", colony: "AQUILES CORDOBA MORAN" },
  { region: "REGION 1", quadrant: "11", colony: "BARRIO SAN ANTONIO" },
  { region: "REGION 1", quadrant: "11", colony: "CONJUNTO HABITACIONAL PARK" },
  { region: "REGION 1", quadrant: "11", colony: "EDIFICIOS SAN JUAN I Y II" },
  { region: "REGION 1", quadrant: "11", colony: "ESTADO DE MEXICO" },
  { region: "REGION 1", quadrant: "11", colony: "HUMBERTO VIDAL" },
  { region: "REGION 1", quadrant: "11", colony: "LA CUEVITA" },
  { region: "REGION 1", quadrant: "11", colony: "SAN ANTONIO TLALPIZAHUAC" },
  { region: "REGION 1", quadrant: "11", colony: "TLACAELEL" },
  { region: "REGION 1", quadrant: "12", colony: "CITLALMINA" },
  { region: "REGION 1", quadrant: "12", colony: "ILHUICAMINA" },
  { region: "REGION 1", quadrant: "12", colony: "LUIS DONALDO COLOSIO" },
  { region: "REGION 1", quadrant: "12", colony: "RANCHO EL CARMEN" },
  { region: "REGION 1", quadrant: "12", colony: "RANCHO GUADALUPE" },
  { region: "REGION 1", quadrant: "12", colony: "RIGOBERTA MENCHU" },
  { region: "REGION 1", quadrant: "12", colony: "VILLAS DE AYOTLA" },
  { region: "REGION 1", quadrant: "13", colony: "6 DE JUNIO" },
  { region: "REGION 1", quadrant: "13", colony: "AMPLIACION 6 DE JUNIO" },
  { region: "REGION 1", quadrant: "13", colony: "CERRO EL PINO" },
  { region: "REGION 1", quadrant: "13", colony: "LUIS CORDOBA REYES" },
  { region: "REGION 1", quadrant: "13", colony: "REY ITZCOATL (I, II Y III)" },
  { region: "REGION 1", quadrant: "14", colony: "AMPLIACION LUIS CORDOBA REYES" },
  { region: "REGION 1", quadrant: "14", colony: "EL MIRADOR" },
  { region: "REGION 1", quadrant: "14", colony: "EL MIRTO" },
  { region: "REGION 1", quadrant: "14", colony: "FERMIN ALVAREZ" },
  { region: "REGION 1", quadrant: "14", colony: "LAVADEROS" },
  { region: "REGION 1", quadrant: "14", colony: "LOMAS DE AYOTLA" },
  { region: "REGION 1", quadrant: "14", colony: "PINO" },
  { region: "REGION 1", quadrant: "14", colony: "PRIMERO DE MAYO" },
  { region: "REGION 1", quadrant: "15", colony: "CASERIO IZCALLI" },
  { region: "REGION 1", quadrant: "15", colony: "CONJUNTO HABITACIONAL EL CALVARIO" },
  { region: "REGION 1", quadrant: "15", colony: "EL CALVARIO" },
  { region: "REGION 1", quadrant: "15", colony: "IXTAPALUCA IZCALLI" },
  { region: "REGION 1", quadrant: "15", colony: "JARDINES IZCALLI" },
  { region: "REGION 1", quadrant: "15", colony: "LA CAÑADA IZCALLI" },
  { region: "REGION 1", quadrant: "15", colony: "LA RETAMA" },
  { region: "REGION 1", quadrant: "15", colony: "POBLADO DE AYOTLA" },
  { region: "REGION 1", quadrant: "15", colony: "RINCON DEL BOSQUE" },
  { region: "REGION 1", quadrant: "15", colony: "VERGEL DE GUADALUPE IZCALLI" },
  { region: "REGION 1", quadrant: "16", colony: "AMPLIACION ACOZAC" },
  { region: "REGION 1", quadrant: "16", colony: "AMPLIACION EL CAPULIN" },
  { region: "REGION 1", quadrant: "16", colony: "AMPLIACION LOMA BONITA" },
  { region: "REGION 1", quadrant: "16", colony: "AMPLIACION SANTO TOMAS" },
  { region: "REGION 1", quadrant: "16", colony: "BUENA VISTA" },
  { region: "REGION 1", quadrant: "16", colony: "EL CAPULIN" },
  { region: "REGION 1", quadrant: "16", colony: "LINDA VISTA" },
  { region: "REGION 1", quadrant: "16", colony: "MARCO ANTONIO SOSA" },
  { region: "REGION 1", quadrant: "16", colony: "NOPALITO" },
  { region: "REGION 1", quadrant: "16", colony: "NOPALERA" },
  { region: "REGION 1", quadrant: "16", colony: "NUEVA ANTORCHISTA" },
  { region: "REGION 1", quadrant: "16", colony: "UNION ANTORCHISTA" },
  { region: "REGION 1", quadrant: "17", colony: "INDEPENDENCIA" },
  { region: "REGION 1", quadrant: "17", colony: "LOMA BONITA" },
  { region: "REGION 1", quadrant: "17", colony: "MAGISTERIO" },
  { region: "REGION 1", quadrant: "17", colony: "SANTO TOMAS" },

  // REGION 2
  { region: "REGION 2", quadrant: "21", colony: "SAN JUAN TLALPIZAHUAC" },
  { region: "REGION 2", quadrant: "21", colony: "SANTA CRUZ TLALPIZAHUAC" },
  { region: "REGION 2", quadrant: "22", colony: "CENTRAL DE ABASTOS AYOTLA" },
  { region: "REGION 2", quadrant: "22", colony: "EL PILAR" },
  { region: "REGION 2", quadrant: "22", colony: "EMILIANO ZAPATA" },
  { region: "REGION 2", quadrant: "22", colony: "MANUEL SERRANO" },
  { region: "REGION 2", quadrant: "22", colony: "RESIDENCIAL AYOTLA" },
  { region: "REGION 2", quadrant: "23", colony: "FRACCIONAMIENTO JOSE DE LA MORA" },
  { region: "REGION 2", quadrant: "23", colony: "PLAZA PATIO AYOTLA" },
  { region: "REGION 2", quadrant: "24", colony: "AMPLIACION EMILIANO ZAPATA" },
  { region: "REGION 2", quadrant: "25", colony: "EL MOLINO" },

  // REGION 3
  { region: "REGION 3", quadrant: "31", colony: "SANTA CRUZ TLAPACOYA" },
  { region: "REGION 3", quadrant: "32", colony: "ALFREDO DEL MAZO NORTE" },
  { region: "REGION 3", quadrant: "32", colony: "AMPLIACION SANTA CRUZ TLAPACOYA" },
  { region: "REGION 3", quadrant: "33", colony: "ALFREDO DEL MAZO SUR" },
  { region: "REGION 3", quadrant: "34", colony: "GEOVILLAS DE SANTA BARBARA NORTE" },
  { region: "REGION 3", quadrant: "35", colony: "GEOVILLAS DE SANTA BARBARA SUR" },
  { region: "REGION 3", quadrant: "36", colony: "PALMAS I II Y III" },
  { region: "REGION 3", quadrant: "37", colony: "DEPORTIVO EMILIANO ZAPATA" },
  { region: "REGION 3", quadrant: "37", colony: "EJIDO EL CAPULIN" },
  { region: "REGION 3", quadrant: "37", colony: "LA VENTA" },
  { region: "REGION 3", quadrant: "37", colony: "PLAZA SENDERO Y PLAZA EL CORTIJO" },
  { region: "REGION 3", quadrant: "37", colony: "ZONA INDUSTRIAL NORTE" },
  { region: "REGION 3", quadrant: "38", colony: "20 DE NOVIEMBRE" },
  { region: "REGION 3", quadrant: "38", colony: "ZONA INDUSTRIAL SUR" },

  // REGION 4
  { region: "REGION 4", quadrant: "41", colony: "CERRO DEL TEJOLOTE" },
  { region: "REGION 4", quadrant: "41", colony: "ESCALERILLA" },
  { region: "REGION 4", quadrant: "41", colony: "U.H. LOMAS DE IXTAPALUCA" },
  { region: "REGION 4", quadrant: "41", colony: "VALLE VERDE" },
  { region: "REGION 4", quadrant: "42", colony: "AMPLIACION ESCALERILLA" },
  { region: "REGION 4", quadrant: "42", colony: "AMPLIACION MORELOS" },
  { region: "REGION 4", quadrant: "42", colony: "EL MIRADOR" },
  { region: "REGION 4", quadrant: "42", colony: "MELCHOR OCAMPO" },
  { region: "REGION 4", quadrant: "42", colony: "MORELOS" },
  { region: "REGION 4", quadrant: "43", colony: "AMPLIACION CONTADERO" },
  { region: "REGION 4", quadrant: "43", colony: "AMPLIACION RICARDO CALVA" },
  { region: "REGION 4", quadrant: "43", colony: "ARBOLEDAS" },
  { region: "REGION 4", quadrant: "43", colony: "CERRO DE MOCTEZUMA" },
  { region: "REGION 4", quadrant: "43", colony: "CONTADERO" },
  { region: "REGION 4", quadrant: "43", colony: "GUADALUPANA" },
  { region: "REGION 4", quadrant: "43", colony: "HUMBERTO CORONA GUTIERREZ" },
  { region: "REGION 4", quadrant: "43", colony: "WENCESLAO VICTORIA SOTO" },
  { region: "REGION 4", quadrant: "44", colony: "AMPLIACION PLUTARCO ELIAS CALLES" },
  { region: "REGION 4", quadrant: "44", colony: "EL RAYO" },
  { region: "REGION 4", quadrant: "44", colony: "ELSA CORDOBA MORAN" },
  { region: "REGION 4", quadrant: "44", colony: "ESPARTACO" },
  { region: "REGION 4", quadrant: "44", colony: "LOMAS PLUTARCO ELIAS CALLES (LOMAS DEL RAYO)" },
  { region: "REGION 4", quadrant: "44", colony: "PLUTARCO ELIAS CALLES" },
  { region: "REGION 4", quadrant: "44", colony: "RICARDO CALVA" },
  { region: "REGION 4", quadrant: "45", colony: "RESIDENCIAL ACOZAC" },
  { region: "REGION 4", quadrant: "46", colony: "GEOVILLAS DE JESUS MARIA" },
  { region: "REGION 4", quadrant: "47", colony: "ARBOLADAS" },
  { region: "REGION 4", quadrant: "47", colony: "EJIDO CARACOL" },
  { region: "REGION 4", quadrant: "47", colony: "IXTAPALUCA 2000" },
  { region: "REGION 4", quadrant: "47", colony: "TLAYEHUALE" },
  { region: "REGION 4", quadrant: "48", colony: "HORNOS SANTA BARBARA" },
  { region: "REGION 4", quadrant: "48", colony: "LA HUERTA" },
  { region: "REGION 4", quadrant: "48", colony: "LA MAGDALENA" },

  // REGION 5
  { region: "REGION 5", quadrant: "51", colony: "EJIDO LA VIRGEN" },
  { region: "REGION 5", quadrant: "51", colony: "GEOVILLAS DE SAN JACINTO" },
  { region: "REGION 5", quadrant: "51", colony: "IXTAPALUCA CENTRO" },
  { region: "REGION 5", quadrant: "51", colony: "SAN JOSE LA PALMA" },
  { region: "REGION 5", quadrant: "52", colony: "CAPILLAS I III Y IV" },
  { region: "REGION 5", quadrant: "52", colony: "LA ERA" },
  { region: "REGION 5", quadrant: "52", colony: "REAL DEL CAMPO" },
  { region: "REGION 5", quadrant: "52", colony: "RESIDENCIAL JACARANDAS I Y II" },
  { region: "REGION 5", quadrant: "52", colony: "SANTA BARBARA" },
  { region: "REGION 5", quadrant: "53", colony: "TEZONTLE" },
  { region: "REGION 5", quadrant: "53", colony: "ZOQUIAPAN PARTE NORTE" },
  { region: "REGION 5", quadrant: "54", colony: "SOLAR DEL GATO" },
  { region: "REGION 5", quadrant: "54", colony: "ZOQUIAPAN SUR" },

  // REGION 6
  { region: "REGION 6", quadrant: "61", colony: "LOS HEROES SUR" },
  { region: "REGION 6", quadrant: "62", colony: "LOS HEROES CASITAS" },
  { region: "REGION 6", quadrant: "62", colony: "LOS HEROES NORTE" },
  { region: "REGION 6", quadrant: "63", colony: "LA ROSA DE SAN FRANCISCO" },
  { region: "REGION 6", quadrant: "63", colony: "ZONA ORIENTE RESIDENCIAL ACOZAC CLUB DE GOLF EJIDO JESUS MARIA" },
  { region: "REGION 6", quadrant: "64", colony: "AMPLIACION ZOQUIAPAN" },
  { region: "REGION 6", quadrant: "64", colony: "CARRIL DE ZOQUIAPAN" },
  { region: "REGION 6", quadrant: "64", colony: "CARRIL DEL VENADO" },
  { region: "REGION 6", quadrant: "64", colony: "EL CARMEN" },
  { region: "REGION 6", quadrant: "64", colony: "EL TABLON" },
  { region: "REGION 6", quadrant: "64", colony: "LOS CARRILES" },
  { region: "REGION 6", quadrant: "64", colony: "LOS DEPOSITOS" },
  { region: "REGION 6", quadrant: "64", colony: "PUENTE DEL MEZQUITE" },
  { region: "REGION 6", quadrant: "64", colony: "RANCHO CHILILICO" },
  { region: "REGION 6", quadrant: "65", colony: "AMPLIACION TEJALPA" },
  { region: "REGION 6", quadrant: "65", colony: "EL OCOTE" },
  { region: "REGION 6", quadrant: "65", colony: "JUAN ANTONIO SOBERANES" },
  { region: "REGION 6", quadrant: "65", colony: "LA PRESA" },
  { region: "REGION 6", quadrant: "65", colony: "PARAJE LOS OLIVARES" },
  { region: "REGION 6", quadrant: "65", colony: "POBLADO DE SAN FRANCISCO" },
  { region: "REGION 6", quadrant: "65", colony: "TEJALPA" },
  { region: "REGION 6", quadrant: "66", colony: "AMPLIACION SAN FRANCISCO" },
  { region: "REGION 6", quadrant: "66", colony: "EL MIRADOR" },
  { region: "REGION 6", quadrant: "66", colony: "HORNOS DE SAN FRANCISCO" },
  { region: "REGION 6", quadrant: "66", colony: "LA VIRGEN" },
  { region: "REGION 6", quadrant: "66", colony: "PIEDRAS GRANDES" },
  { region: "REGION 6", quadrant: "66", colony: "UPREZ" },
  { region: "REGION 6", quadrant: "67", colony: "PUEBLO DE COATEPEC" },
  { region: "REGION 6", quadrant: "67", colony: "RANCHO VERDE" },
  { region: "REGION 6", quadrant: "67", colony: "SAN JUAN" },
  { region: "REGION 6", quadrant: "67", colony: "TETITLA" },
  { region: "REGION 6", quadrant: "67", colony: "FRANCISCO SANTILLAN" },
  { region: "REGION 6", quadrant: "68", colony: "PEÑA DE LA ROSA DE CASTILLA" },
  { region: "REGION 6", quadrant: "68", colony: "PUEBLO NUEVO" },
  { region: "REGION 6", quadrant: "68", colony: "VOLCANES" },
  { region: "REGION 6", quadrant: "68", colony: "INDEPENDENCIA" },
  { region: "REGION 6", quadrant: "68", colony: "LOMAS DE COATEPEC" },

  // REGION 7
  { region: "REGION 7", quadrant: "71", colony: "CARRIL DEL GATO" },
  { region: "REGION 7", quadrant: "71", colony: "SAN BUENAVENTURA PONIENTE" },
  { region: "REGION 7", quadrant: "72", colony: "SAN BUENAVENTURA ORIENTE" },
  { region: "REGION 7", quadrant: "73", colony: "AMPLIACION JORGE JIMENEZ CANTU" },
  { region: "REGION 7", quadrant: "73", colony: "AMPLIACION ZOQUIAPAN" },
  { region: "REGION 7", quadrant: "73", colony: "EL PATRONATO" },
  { region: "REGION 7", quadrant: "73", colony: "EL TEZOYO" },
  { region: "REGION 7", quadrant: "73", colony: "HORNOS DE ZOQUIAPAN" },
  { region: "REGION 7", quadrant: "73", colony: "JORGE JIMENEZ CANTU" },
  { region: "REGION 7", quadrant: "73", colony: "LA CAÑADA" },
  { region: "REGION 7", quadrant: "73", colony: "TEPONAZTLE" },
  { region: "REGION 7", quadrant: "74", colony: "MARGARITA MORAN" },
  { region: "REGION 7", quadrant: "74", colony: "SAN JERONIMO CUATRO VIENTOS" },
  { region: "REGION 7", quadrant: "74", colony: "VILLAS DE ANTORCHA" },
  { region: "REGION 7", quadrant: "75", colony: "C. U. CUATRO VIENTOS" },
  { region: "REGION 7", quadrant: "75", colony: "CUMBRES DE LA MONTAÑA" },
  { region: "REGION 7", quadrant: "76", colony: "GRAL. AVILA CAMACHO" },
  { region: "REGION 7", quadrant: "76", colony: "LA LOBERA O SAN ISIDRO" },
  { region: "REGION 7", quadrant: "76", colony: "LLANO GRANDE" },
  { region: "REGION 7", quadrant: "77", colony: "RIO FRIO" }
];
